version: '3.8'

services:
  db:
    container_name: db # add a name for the container
    image: mysql:latest # use latest version of mysql
    ports:
      - '3306:3306'
    environment: # add default values, see docs for more info.
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: testdb # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password


  go:
    container_name: go
    build: # Use the Dockerfile from the current directory to build container.
      context: ./backend
    restart: always
    ports: 
      - "8080:8080"
    depends_on: 
      - "db"
    volumes:
      - mobile:/home/go

  web:
    container_name: web
    build: # Use the Dockerfile from the current directory to build container.
      context: ./web/web-app
    ports:
      - "3000:3000"
    depends_on:
      - "go"
    volumes:
      - mobile:/home/web

  mobile:
    container_name: mobile
    build: # Use the Dockerfile from the current directory to build container.
      context: ./mobile/
    devices:
      - /dev/tty
    depends_on:
      - "go"
    network_mode: "host"
    privileged: true
    volumes:
      - mobile:/home/mobile

volumes: # add volume to persist data.
  mobile:
  my-db:

